### ISSUE TITLE
error: argument -a/--album-levels: expected one argument`

### ISSUE THREAD

**Issue by dushyantahuja** [Salvoxia/immich-folder-album-creator#29]
`python immich_auto_album.py -a '-2,-3' -s ":" /home/users/Archive http://****:2283/api ***************** `

gives the following error:

`immich_auto_album.py: error: argument -a/--album-levels: expected one argument`

Am using the bare metal script (have just downloaded it) and installed. Not sure what the best way is.

Thanks for your help

**Comment by Salvoxia** [comment]
Hi,

sorry you're having problems with the script.
When using negative album level ranges you must follow a specific syntax for passing the argument to the script, otherwise the arguments parser gets a hiccup and throws the error you experienced.
Try this:
`python immich_auto_album.py -a='-2,-3' -s ":" /home/users/Archive http://****:2283/api *****************`
Emphasis is on the equals sign `=` separating the argument name from the value.

I updated the readme to draw attention to this special case.

**Comment by dushyantahuja** [comment]
Not at all - it's an amazing script. And thanks for being so proactive.
