### ISSUE TITLE
How does the script work with changes in the external library after inital albums creation?

### ISSUE THREAD

**Issue by wechsler42** [Salvoxia/immich-folder-album-creator#33]
Hello,
thanks Salvoxia for providing this Python script! What a relief.

I wonder how the Python script will act on situations like these:
After inital and successful creation of Immich albums from a given directory structure in an external library the script is periodically rerun (cron job). Now it may face situations like
1. Some photos were deleted in a directory within the external libray
2. Some photos are changed (e.g. metadata of a jpeg was overwritten)
3. A whole directory including its photos was deleted within the external library
4. Some photos were moved from one drectory to another in the external library

How would the album display in Immich react on the events 1.-4 in the external library?

**Comment by janwdev** [comment]
Hey, I just played with the script a little bit and came across the same questions you have! As far as I have observed, the script does not recognize if you remove pictures from a directory or the whole directory from an external library.
My solution for now is to use the cleanup option of the script and recreate all albums. This also works if you have modified images inside the album.
I have to admit that this is more of a workaround and I also realized 3 big downsides of this approach.
1. The mobile app loads all newly created albums very slowly, which is bad after a recreation.
2. Because of this, I only run the cleanup once a month, which is fine for me, but results in corrupt albums during that time period.
3. It removes all shares from the albums, as the albums are re-created with each cleanup.

I decided to post my workaround here anyway, in case it is good enough for you until there is a better solution, maybe it can help you.

**Comment by Salvoxia** [comment]
Hi,

when considering these questions it's important to know what the source of truth for the script is: the Immich API.
Keeping that in mind:
> 1. Some photos were deleted in a directory within the external libray

The script will do nothing, since Immich will still know of that asset, but will has marked it as 'offline'. So the asset still exists and is still assigned to its album.

>2.  Some photos are changed (e.g. metadata of a jpeg was overwritten)

The script will do nothing, since this is not relevant for the script.

> 3. A whole directory including its photos was deleted within the external library

Kinda similar to the first case, but now Immich will mark all photos in that album as 'offline. The album still exists and still shows all the assets (at least as thumbnails).

> 4. Some photos were moved from one drectory to another in the external library

This is the only case where it gets a little messy: Again, Immich will still know the asset in its original folder and mark it as offline, but also detect the asset in its new folder, and so will the script. A new album will be generated from the new folder and the new assets added to it.

It sounds to me like all these cases could be caught by adding a simple, optional routine: Triggering removal of offline assets for all detected external libraries as well as deleting all empty albums. Since offline asset removal is an asynchronous job, deleting empty albums would catch on during subsequent runs, but would get rid of albums that became empty due to photos being deleted or moved to other folder (along with all other empty albums, unfortunately).  
That would fix all inconsistencies created by cases 1, 3 and 4., even though it is somewhat aggressive and MIGHT interfere with albums not originally created by the script.

What do you think?

Best Regards,
Salvoxia

**Comment by wechsler42** [comment]
Hello Salvoxia,
thanks for detailed feedback.
Regarding your suggestion of an optional triggering routine for the cases 1, 3 and 4, I would appreciate that. It would probably also circumvent some drawbacks of the method @janwdev mentioned in https://github.com/Salvoxia/immich-folder-album-creator/issues/33#issuecomment-2291126013 .
Thanks again for your work.,

**Comment by Salvoxia** [comment]
Hey guys,

this is now implemented on the `dev` branch and the `edge` Docker image tag. I'd a appreciate if you could give it a try and come back with some feedback before baking it in a new release.
The documentation on how it's supposed to work is here: https://github.com/Salvoxia/immich-folder-album-creator/tree/dev?tab=readme-ov-file#dealing-with-external-library-changes

Best Regards,
Salvoxia

**Comment by wechsler42** [comment]
Hello Salvoxia,
thanks for your work on extending the script for the uses cases1, 3 and 4 mentioned at the beginning of this thread. I "played" the last days with the plain Python script (no Docker image) from the dev branch with regard to the mentioned use cases. All worked fine, I found no errors.  Thanks again for your work!

**Comment by Salvoxia** [comment]
Released in [0.9.0](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.9.0).
