### ISSUE TITLE
Sync mode

### ISSUE THREAD

**Issue by tamimology** [Salvoxia/immich-folder-album-creator#46]
I liked the update where I can specify the sync mode as 0, 1 or 2
In my opinion, and as I needed that, I suggest to haveca mode 3 where you combine adding new assets to albums as well as performing a clean up for offline assets and empty albums

I know it can be achieved by having another container with a different sync mode, but having it in 1 container will lower resources used by 2 containers as well as less containers quantities 🤗

**Comment by Salvoxia** [comment]
Hi,

thanks for the positive feedback, it means a lot!
I agree that even though the container already has a very small footprint (~10MiB memory) less containers is better. However, this comes with two points to keep in mind:
 - only works if the user you are creating folder for is an Immich admin
 - deleting empty albums will most certainly "lag behind" one cron cycle since Offline Asset Removal is not instantaneous

On the other hand, I saw the Immich team introducing granular API Key permissions on the server side, so it might be possible to grant a "normal" user's API key the permission to trigger Offline Asset Removal as well. For now, there is now such permission and the client side does not yet support creating API keys with anything but all permissions.

When thinking about the two points I mentioned, would this function still be of use for you?

Best Regards,
Salvoxia

**Comment by Salvoxia** [comment]
Closing for now due to lack of response.
If you/anyone else is interested in this feature, feel free to reopen/comment here again.
