### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by makipsee** [Salvoxia/immich-folder-album-creator#47]
im sorry to add this as a suggestion, but is there anyway to set this to work for different users? like can one command create albums for one user and another command work for a different user or can it only work for the admin user?

**Comment by Salvoxia** [comment]
Hi,

the script will run for the user whose API Key you pass it. Every user can create API Keys, not only Armin users. The only case where you __need__ an Armin user's API Key is when you want to trigger Offline Asset Removal with Sync Mode 2.  

If you want to run the script for different users, it's straight forward when using the CLI: Simply pass different API Keys.
When running periodically as a container, you need to create one container per user (API Key), potentially with different settings. Due to the low memory footprint of about 10MiB I do not (yet) see this is as a problem, compared to the required effort of supporting different configurations with a single container.

Besteht Regards,
Salvoxia

**Comment by makipsee** [comment]
Ooo ok I understand now! Thank you for the response!!
