### ISSUE TITLE
Feature request: Set the album description

### ISSUE THREAD

**Issue by mspoorendonk** [Salvoxia/immich-folder-album-creator#64]
I have album descriptions in text files inside the folder structure that defines my albums on disk. Would be great if your script would read those. Preferably using a standard format. (I will then make sure to first convert my proprietary files (such as picasa.ini files) to this standard.

**Comment by Salvoxia** [comment]
Thank you for your suggestion!
I think I'll have to disappoint you, though. This feature would require the script to have direct access to the files that are mounted as external library into the Immich container. The design philisophy at the moment is to only interact with Immich's API, which can happen from anywhere the Immich API can be reached from. The script does not have to run on the same server and there are no permissions to take care of.  

Unless such a feature is requested by many people, I don't think it will be added.  
Sorry.

**Comment by Kernald** [comment]
Just replying because of this:

> Unless such a feature is requested by many people, I don't think it will be added.

I was about to request a similar feature, where a text file at the root of an album would be able to override e.g. the album title if present, or listing the name of a specific asset of the album to use as a thumbnail. So, yeah - at least plus one person requesting this. I feel like this could be added as an optional argument for the local path to the data, and a pretty simple match (e.g. if Immich sees the external library as `/mnt/photos` but my laptop on which I'm calling this has it mounted as `/Volumes/photos`, calling this script with `/mnt/photos --local /Volumes/photos`, matching local and remote assets is as simple as removing the relevant prefix).

I definitely appreciate that it's a bit of a departure from the way it works at the moment though.

**Comment by Salvoxia** [comment]
By setting `--album-levels` as a range it's possible to have assets from multiple folders added to the same album. How would you expect the script to behave in such cases?  
Thinking hypothetically at the moment.

**Comment by Kernald** [comment]
That's a fair question - I'm not using ranges so I hadn't thought of it. I feel like it's an edge case that, as long as it's well defined (and documented), doesn't matter _too_ much - maybe consider only text files at the root of what would eventually create the album? E.g. if `foo`, `foo/bar`, `foo/bar/baz` and `foo/qux` were ending in a single `foo` album, only a `foo/.albumprops` (or whatever name) file would be considered. Raising a warning if a `foo/bar/.albumprops` was found but not used would also make it obvious when something like that is going on.

**Comment by Kernald** [comment]
This sounds great! I'm just wondering, in terms of the album cover, if we could instead (or in addition to the currently planned options) refer to a specific asset by filename? I understand that the current options are what currently exist in this script, hence simpler to implement, so maybe an idea for the future, but designing the configuration file with that in mind might be nice.

**Comment by Salvoxia** [comment]
Thanks for your feedback! Doesn't sound too bad in terms of effort. However, due to the possibility of multiple files from different folders present in the same album, a simple file name might not be unique. Furthermore, taking the possibility of multiple root paths into account well, it would have to be a fully qualified path to actually be unique in any case.
With some kind of fallback if the file does not exist.
What do you think?

**Comment by Kernald** [comment]
Fully qualified path sounds good yeah!

**Comment by Salvoxia** [comment]
A working prototype is available in branch [feat/advancedAlbumProps](https://github.com/Salvoxia/immich-folder-album-creator/tree/feat/advancedAlbumProps).
It needs to be polished (linting fails) and tested more.
Option `--read-album-properties` is still missing.
Docker not yet updated.

Otherwise, should be functioning.

Tests and feedback are much appreciated!

**Comment by Salvoxia** [comment]
Implemented with #87, pending release.

**Comment by Salvoxia** [comment]
Release with version [0.16.0](https://github.com/Salvoxia/immich-folder-album-creator/releases/tag/0.16.0).
