### ISSUE TITLE
Install immich-folder-album-creator on other system than Immich server?

### ISSUE THREAD

**Issue by lagge78** [Salvoxia/immich-folder-album-creator#65]
Hello!
I have a Immich server running in Homeassistant OS as an Add-on.
As  immich-folder-album-creator isn't installable as an Add-on I though that I could set it up as a docker on my NAS instead but I cant get it to work.

Is it possible to have immich-folder-album-creator running as a docker in another host and connect via ip+ API key? I see that the docker compose example shown a stack with both immich-server and immich-folder-album-creator together. Is that needed to get it to work?

Thanks!
Br Fredrik

**Comment by Salvoxia** [comment]
You can run immich-folder-album-creator from anywhere the Immich API can be reached from, so yes, what you are trying to do ia absolutey possible.
The examples with the docker-compse file using the Immich stack is just meant for convience for people who have Immich deployed that way.

If you can post what you already tried and what errors you get, I'm sure we can get it to work.

**Comment by lagge78** [comment]
Great, thanks! Itried it like below and the container starts OK and goes to running, but when I open it in Portainer and press logs its empty, normally in my other containers I see the container starting up with some running info. And if I enter Immich I cant see anything being created. 

How I set it up:
Actual path locally on the NAS where the photos are stored: 
/volume1/homes/user-name/Photos/PhotoLibrary

The homes folder above is shared from the NAS as a Samba share.
In Homeassistant I have added this homes folder under /share as a network drive.
So for HA the pictures are accessable under /share/homes/user-name/Photos/PhotoLibrary

In the HAOS Immich add-on, the same directory is mapped as a localdisks:
/share/Homes/flsmedberg/Photos/PhotoLibrary

Then in Immich I added /share/Homes/flsmedberg/Photos/PhotoLibrary as an External Library.

Then I tried this docker-compose code on the NAS:

name: immich-folder-album-creator
services:
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    volumes:
     - /volume1/homes/user-name/Photos/PhotoLibrary:/share/homes/user-name/Photos/PhotoLibrary    
    environment:
      API_URL: http://192.168.1.180:8182/api
      API_KEY: xxxxxxxxxx
      ROOT_PATH: /share/homes/user-name/Photos/PhotoLibrary
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Stockholm

Any idea?

Br Fredrik

**Comment by Salvoxia** [comment]
The container actually will not log anything until the script has run at least once. You set the `CRON_EXPRESSION` so that it runs every full hour, so you'll have to wait for that to pass to see any log output. Unless of course it already has run that long and you still cannot see anything, then something's wrong.

FYI: You don't need to mount your library as a volume into the container. It gets all information it needs from the Immich API.

You can open a console into the container from Portainer and try running
```bash
./immich-folder-album.sh
```
That is a dry-run using the settings passed to the container with your environment variables, so it will only tell you what it __would__ do without actually doing anything. Output from the dry-run will __not__ show int he container's logs either. But at least then you know it's going to do what you want it to when the cronjob hits.

**Comment by lagge78** [comment]
It worked, I left it alone a couple of hours and now I have a bunch of new albums. 😃👌
Thank you very much for the guidance and support.
Have a nice weekend!
