### ISSUE TITLE
0 photos found

### ISSUE THREAD

**Issue by machitza** [Salvoxia/immich-folder-album-creator#75]
I' doing something wrong... please help if you would.

(my-venv) root@cf21b3406327:~# my-venv/bin/python3 ./immich_auto_album.py -r /media /media/2024/01-04.05.2024.Cheile.Dobrogei.Vadu/04.05.2024.Vadu http://localhost:2283/api cxZDIbqb4Ns3bxTSMVM9QC1pynrXbYnIWLUo7lnRA -l DEBUG
time=2024-10-30T13:38:58.673+02:00 level=DEBUG msg=root_path = ['/media', '/media/2024/01-04.05.2024.Cheile.Dobrogei.Vadu/04.05.2024.Vadu']
time=2024-10-30T13:38:58.673+02:00 level=DEBUG msg=root_url = http://localhost:2283/api
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=api_key = cxZDIbqb4Ns3bxTSMVM9QC1pynrXbYnIWLUo7lnRA
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=number_of_images_per_request = 2000
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=number_of_assets_to_fetch_per_request = 5000
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=unattended = False
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=album_levels = 1
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=album_level_separator =
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=album_order = False
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=insecure = False
time=2024-10-30T13:38:58.674+02:00 level=DEBUG msg=ignore = None
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=mode = CREATE
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=delete_confirm = False
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=is_docker = False
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=share_with = None
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=share_role = viewer
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=sync_mode = 0
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=find_assets_in_albums = False
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=path_filter = None
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=set_album_thumbnail = None
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=archive = False
time=2024-10-30T13:38:58.675+02:00 level=DEBUG msg=find_archived_assets = False
time=2024-10-30T13:38:58.678+02:00 level=DEBUG msg=Starting new HTTP connection (1): localhost:2283
time=2024-10-30T13:38:58.681+02:00 level=DEBUG msg=http://localhost:2283 "GET /api/server/version HTTP/11" 200 33
time=2024-10-30T13:38:58.682+02:00 level=INFO msg=Detected Immich server version 1.119.1
time=2024-10-30T13:38:58.682+02:00 level=INFO msg=Requesting all assets
time=2024-10-30T13:38:58.684+02:00 level=DEBUG msg=Starting new HTTP connection (1): localhost:2283
time=2024-10-30T13:38:58.714+02:00 level=DEBUG msg=http://localhost:2283 "POST /api/search/metadata HTTP/11" 200 125
time=2024-10-30T13:38:58.714+02:00 level=DEBUG msg=Received 0 assets with chunk 1
time=2024-10-30T13:38:58.715+02:00 level=INFO msg=0 photos found
time=2024-10-30T13:38:58.715+02:00 level=INFO msg=Sorting assets to corresponding albums using folder name
time=2024-10-30T13:38:58.715+02:00 level=INFO msg=0 albums identified
time=2024-10-30T13:38:58.715+02:00 level=INFO msg=Album list: []
Press enter to create these albums, Ctrl+C to abort

time=2024-10-30T13:38:59.833+02:00 level=INFO msg=Listing existing albums on immich
time=2024-10-30T13:38:59.836+02:00 level=DEBUG msg=Starting new HTTP connection (1): localhost:2283
time=2024-10-30T13:38:59.857+02:00 level=DEBUG msg=http://localhost:2283 "GET /api/albums HTTP/11" 200 2
time=2024-10-30T13:38:59.858+02:00 level=INFO msg=0 existing albums identified
time=2024-10-30T13:38:59.858+02:00 level=INFO msg=Creating albums if needed
time=2024-10-30T13:38:59.858+02:00 level=INFO msg=0 albums created
time=2024-10-30T13:38:59.859+02:00 level=INFO msg=Adding assets to albums
time=2024-10-30T13:38:59.859+02:00 level=INFO msg=Done!

(my-venv) root@ed20b6d30c97:~# ls /media/2024/01-04.05.2024.Cheile.Dobrogei.Vadu/04.05.2024.Vadu 
25238f4f-5524-4d58-93fa-92e6a780b1b3.JPG  

/media folder in mapped to my host at /media/dsm/Pictures

**Comment by Salvoxia** [comment]
Hi

`time=2024-10-30T13:38:58.714+02:00 level=DEBUG msg=Received 0 assets with chunk 1`

indicates that there are actually no assets for the user the API key belongs to, which are __not already part of an album__ and are __not archived__.
By default the script will not find any assets that are already assigned to an album and/or are marked as `archived` in Immich.

The root path might not be right as well since you specify two root paths `/media` and `/media/2024/01-04.05.2024.Cheile.Dobrogei.Vadu/04.05.2024.Vadu`, where the first already contains the second. But that is a different problem, first we need to make sure the script actually receives any assets from the Immich API.

So can you check with the user the API key belongs to whether there are actually images present in Immich, and if so, if these images are either already in some other album and/or are archived?

If you want the script to find those as well, you need to pass `--find-assets-in-albums` and/or `--find-archived-assets`.

Best Regards
Salvoxia

**Comment by machitza** [comment]
got it now... thanks
